name: Deploy to Beta Environment
'on':
  push:
    branches:
      - development
jobs:
  Beta-Deployment:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
    
    - name: Build Steps                                                   
      run: |
        echo "Build stage"
        
    - name: AWS Deployment
      uses: reggionick/s3-deploy@v3
      with:
          folder: build
          bucket: cloudfronts3007
          bucket-region: ap-southeast-1
          dist-id: EWKNQBYI44IYP
          invalidation: /
