name: Deploy to Beta Environment
'on':
  push:
    branches:
      - development
jobs:
  Beta-Deployment:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "ap-southeast-1"
    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
    
    - name: Build Steps                                                   
      run: |
        echo "Build stage"
        
    - name: Invalidate CloudFront
      uses: chetan/invalidate-cloudfront-action@v2
      env:
        DISTRIBUTION: EWKNQBYI44IYP
        PATHS: "/"
